### ISSUE TITLE
Change font and font sizes

### ISSUE THREAD

**Issue by Dvisik** [cocopon/tweakpane#395]
Is it possible to change default font to different Google font and font size?

**Comment by cocopon** [comment]
There is not the official way, but you can use CSS to change the style. Example:

```css
:root {
  --tp-font-family: Couriter;
}
.tp-rotv {
  font-size: 12px;
}
```
